### ISSUE TITLE
onInitData is not a function

### ISSUE THREAD

**Issue by JoonDong2** [Feng-Bu-Jue/react-native-waterfall#3] opened 2020-10-03 18:42 UTC
`onInitData is not a function` error occurred when onInitData is undefined on iOS14.

Thank you for making good library.

**Comment by Feng-Bu-Jue** [comment] 2020-10-04 11:54
Make sure package version is 1.1.8 first?
is only reproduce on ios14? can you provide reproduce sample.( it could fork from [online-demo](https://codesandbox.io/s/waterfall-demo-rxkww?file=/src/App.tsx "Heading link"))

**Comment by JoonDong2** [comment] 2020-10-06 08:16
> Make sure package version is 1.1.8 first?
> is only reproduce on ios14? can you provide a reproduction sample.( it could fork from [online-demo](https://codesandbox.io/s/waterfall-demo-rxkww?file=/src/App.tsx))

yes, I tested it with version 1.18.
This seems to occur when the `itemInfoData` is an empty array and the `onInitData` is `undeinfed`.

Thank you.

**Comment by Feng-Bu-Jue** [comment] 2020-10-06 11:20
please try with version 1.1.9

**Comment by JoonDong2** [comment] 2020-10-06 15:41
> please try with version 1.1.9

This time the same error occurs on android.
it occurs each time `Waterfall` is initialized.

**Comment by Feng-Bu-Jue** [comment] 2021-04-01 08:53
Close the Issue because the prop no longer exists

**Closed by Feng-Bu-Jue** 2021-04-01 08:53 UTC
